/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CataloguingRecord {
  'status' : { 'submitted' : null } |
    { 'draft' : null },
  'additionalInformation' : string,
  'equipmentNumber' : bigint,
  'templateName' : string,
  'attributes' : Array<[string, string]>,
  'materialDescription' : string,
}
export interface Document {
  'documentType' : string,
  'additionalInformation' : string,
  'equipmentNumber' : bigint,
  'filePath' : ExternalBlob,
  'docId' : bigint,
  'uploadDate' : Time,
}
export type EngineeringDiscipline = { 'mechanical' : null } |
  { 'piping' : null } |
  { 'electrical' : null } |
  { 'unknown' : null } |
  { 'instrumentation' : null };
export interface Equipment {
  'model' : string,
  'manufacturer' : string,
  'discipline' : EngineeringDiscipline,
  'purchaseDate' : Time,
  'additionalInformation' : string,
  'name' : string,
  'equipmentNumber' : bigint,
  'serialNumber' : string,
  'warrantyExpiry' : Time,
  'location' : string,
  'equipmentTagNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface MaintenanceRecord {
  'maintenanceStatus' : { 'scheduled' : null } |
    { 'completed' : null } |
    { 'overdue' : null },
  'additionalInformation' : string,
  'equipmentNumber' : bigint,
  'maintenanceType' : string,
  'maintenanceId' : bigint,
  'nextMaintenanceDate' : Time,
  'lastMaintenanceDate' : Time,
}
export interface SparePart {
  'manufacturer' : string,
  'partNumber' : bigint,
  'supplier' : string,
  'additionalInformation' : string,
  'name' : string,
  'equipmentNumber' : bigint,
  'description' : string,
  'modelSerial' : string,
  'quantity' : bigint,
  'attachment' : [] | [ExternalBlob],
  'partNo' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'department' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCataloguingRecord' : ActorMethod<
    [bigint, string, string, Array<[string, string]>, boolean, string],
    [] | [bigint]
  >,
  'createEquipment' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Time,
      Time,
      string,
      EngineeringDiscipline,
    ],
    bigint
  >,
  'createMaintenanceRecord' : ActorMethod<
    [
      bigint,
      string,
      { 'scheduled' : null } |
        { 'completed' : null } |
        { 'overdue' : null },
      Time,
      Time,
      string,
    ],
    [] | [bigint]
  >,
  'createSparePart' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      string,
    ],
    [] | [bigint]
  >,
  'deleteCataloguingRecord' : ActorMethod<[bigint, bigint], boolean>,
  'deleteDocument' : ActorMethod<[bigint, bigint], boolean>,
  'deleteEquipment' : ActorMethod<[bigint], boolean>,
  'deleteMaintenanceRecord' : ActorMethod<[bigint, bigint], boolean>,
  'deleteSparePart' : ActorMethod<[bigint, bigint], boolean>,
  'findSparePartsByEquipmentTagNumber' : ActorMethod<
    [string],
    Array<SparePart>
  >,
  'findSparePartsByManufacturer' : ActorMethod<[string], Array<SparePart>>,
  'findSparePartsByModelSerial' : ActorMethod<[string], Array<SparePart>>,
  'findSparePartsByPartNo' : ActorMethod<[string], Array<SparePart>>,
  'getAllEquipment' : ActorMethod<[], Array<Equipment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCataloguingRecordsByEquipment' : ActorMethod<
    [bigint],
    Array<CataloguingRecord>
  >,
  'getDocumentsByEquipment' : ActorMethod<[bigint], Array<Document>>,
  'getEquipment' : ActorMethod<[bigint], [] | [Equipment]>,
  'getEquipmentList' : ActorMethod<[], Array<Equipment>>,
  'getMaintenanceByEquipment' : ActorMethod<[bigint], Array<MaintenanceRecord>>,
  'getMaintenanceDueReport' : ActorMethod<[], Array<MaintenanceRecord>>,
  'getNextEquipmentNumber' : ActorMethod<[], bigint>,
  'getSparePartsByEquipment' : ActorMethod<[bigint], Array<SparePart>>,
  'getSparePartsReport' : ActorMethod<[], Array<SparePart>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCataloguingRecord' : ActorMethod<
    [bigint, bigint, string, string, Array<[string, string]>, boolean, string],
    boolean
  >,
  'updateDocumentMetadata' : ActorMethod<
    [bigint, bigint, string, string],
    boolean
  >,
  'updateEquipment' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      Time,
      Time,
      string,
      EngineeringDiscipline,
    ],
    boolean
  >,
  'updateMaintenanceRecord' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      { 'scheduled' : null } |
        { 'completed' : null } |
        { 'overdue' : null },
      Time,
      Time,
      string,
    ],
    boolean
  >,
  'updateSparePart' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      string,
    ],
    boolean
  >,
  'uploadDocument' : ActorMethod<
    [bigint, string, ExternalBlob, string],
    [] | [bigint]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];