/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const EngineeringDiscipline = IDL.Variant({
  'mechanical' : IDL.Null,
  'piping' : IDL.Null,
  'electrical' : IDL.Null,
  'unknown' : IDL.Null,
  'instrumentation' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SparePart = IDL.Record({
  'manufacturer' : IDL.Text,
  'partNumber' : IDL.Nat,
  'supplier' : IDL.Text,
  'additionalInformation' : IDL.Text,
  'name' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'description' : IDL.Text,
  'modelSerial' : IDL.Text,
  'quantity' : IDL.Nat,
  'attachment' : IDL.Opt(ExternalBlob),
  'partNo' : IDL.Text,
});
export const Equipment = IDL.Record({
  'model' : IDL.Text,
  'manufacturer' : IDL.Text,
  'discipline' : EngineeringDiscipline,
  'purchaseDate' : Time,
  'additionalInformation' : IDL.Text,
  'name' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'serialNumber' : IDL.Text,
  'warrantyExpiry' : Time,
  'location' : IDL.Text,
  'equipmentTagNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const CataloguingRecord = IDL.Record({
  'status' : IDL.Variant({ 'submitted' : IDL.Null, 'draft' : IDL.Null }),
  'additionalInformation' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'templateName' : IDL.Text,
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'materialDescription' : IDL.Text,
});
export const Document = IDL.Record({
  'documentType' : IDL.Text,
  'additionalInformation' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'filePath' : ExternalBlob,
  'docId' : IDL.Nat,
  'uploadDate' : Time,
});
export const MaintenanceRecord = IDL.Record({
  'maintenanceStatus' : IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
  }),
  'additionalInformation' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'maintenanceType' : IDL.Text,
  'maintenanceId' : IDL.Nat,
  'nextMaintenanceDate' : Time,
  'lastMaintenanceDate' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCataloguingRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'createEquipment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Text,
        EngineeringDiscipline,
      ],
      [IDL.Nat],
      [],
    ),
  'createMaintenanceRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Variant({
          'scheduled' : IDL.Null,
          'completed' : IDL.Null,
          'overdue' : IDL.Null,
        }),
        Time,
        Time,
        IDL.Text,
      ],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'createSparePart' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'deleteCataloguingRecord' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteEquipment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMaintenanceRecord' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteSparePart' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'findSparePartsByEquipmentTagNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'findSparePartsByManufacturer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'findSparePartsByModelSerial' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'findSparePartsByPartNo' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCataloguingRecordsByEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CataloguingRecord)],
      ['query'],
    ),
  'getDocumentsByEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getEquipment' : IDL.Func([IDL.Nat], [IDL.Opt(Equipment)], ['query']),
  'getEquipmentList' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'getMaintenanceByEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getMaintenanceDueReport' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getNextEquipmentNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getSparePartsByEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'getSparePartsReport' : IDL.Func([], [IDL.Vec(SparePart)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCataloguingRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateDocumentMetadata' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateEquipment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Text,
        EngineeringDiscipline,
      ],
      [IDL.Bool],
      [],
    ),
  'updateMaintenanceRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Variant({
          'scheduled' : IDL.Null,
          'completed' : IDL.Null,
          'overdue' : IDL.Null,
        }),
        Time,
        Time,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateSparePart' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'uploadDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, ExternalBlob, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const EngineeringDiscipline = IDL.Variant({
    'mechanical' : IDL.Null,
    'piping' : IDL.Null,
    'electrical' : IDL.Null,
    'unknown' : IDL.Null,
    'instrumentation' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SparePart = IDL.Record({
    'manufacturer' : IDL.Text,
    'partNumber' : IDL.Nat,
    'supplier' : IDL.Text,
    'additionalInformation' : IDL.Text,
    'name' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'description' : IDL.Text,
    'modelSerial' : IDL.Text,
    'quantity' : IDL.Nat,
    'attachment' : IDL.Opt(ExternalBlob),
    'partNo' : IDL.Text,
  });
  const Equipment = IDL.Record({
    'model' : IDL.Text,
    'manufacturer' : IDL.Text,
    'discipline' : EngineeringDiscipline,
    'purchaseDate' : Time,
    'additionalInformation' : IDL.Text,
    'name' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'serialNumber' : IDL.Text,
    'warrantyExpiry' : Time,
    'location' : IDL.Text,
    'equipmentTagNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const CataloguingRecord = IDL.Record({
    'status' : IDL.Variant({ 'submitted' : IDL.Null, 'draft' : IDL.Null }),
    'additionalInformation' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'templateName' : IDL.Text,
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'materialDescription' : IDL.Text,
  });
  const Document = IDL.Record({
    'documentType' : IDL.Text,
    'additionalInformation' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'filePath' : ExternalBlob,
    'docId' : IDL.Nat,
    'uploadDate' : Time,
  });
  const MaintenanceRecord = IDL.Record({
    'maintenanceStatus' : IDL.Variant({
      'scheduled' : IDL.Null,
      'completed' : IDL.Null,
      'overdue' : IDL.Null,
    }),
    'additionalInformation' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'maintenanceType' : IDL.Text,
    'maintenanceId' : IDL.Nat,
    'nextMaintenanceDate' : Time,
    'lastMaintenanceDate' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCataloguingRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'createEquipment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Text,
          EngineeringDiscipline,
        ],
        [IDL.Nat],
        [],
      ),
    'createMaintenanceRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Variant({
            'scheduled' : IDL.Null,
            'completed' : IDL.Null,
            'overdue' : IDL.Null,
          }),
          Time,
          Time,
          IDL.Text,
        ],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'createSparePart' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'deleteCataloguingRecord' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteEquipment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMaintenanceRecord' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteSparePart' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'findSparePartsByEquipmentTagNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'findSparePartsByManufacturer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'findSparePartsByModelSerial' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'findSparePartsByPartNo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCataloguingRecordsByEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CataloguingRecord)],
        ['query'],
      ),
    'getDocumentsByEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getEquipment' : IDL.Func([IDL.Nat], [IDL.Opt(Equipment)], ['query']),
    'getEquipmentList' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'getMaintenanceByEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getMaintenanceDueReport' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getNextEquipmentNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getSparePartsByEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'getSparePartsReport' : IDL.Func([], [IDL.Vec(SparePart)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCataloguingRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateDocumentMetadata' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateEquipment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Text,
          EngineeringDiscipline,
        ],
        [IDL.Bool],
        [],
      ),
    'updateMaintenanceRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Variant({
            'scheduled' : IDL.Null,
            'completed' : IDL.Null,
            'overdue' : IDL.Null,
          }),
          Time,
          Time,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateSparePart' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'uploadDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };