/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CataloguingRecord {
  'status' : { 'submitted' : null } |
    { 'draft' : null },
  'additionalInformation' : string,
  'equipmentNumber' : bigint,
  'templateName' : string,
  'attributes' : Array<[string, string]>,
  'materialDescription' : string,
}
export interface Document {
  'documentType' : string,
  'additionalInformation' : string,
  'equipmentNumber' : bigint,
  'filePath' : ExternalBlob,
  'docId' : bigint,
  'uploadDate' : Time,
}
export type EngineeringDiscipline = { 'mechanical' : null } |
  { 'piping' : null } |
  { 'electrical' : null } |
  { 'unknown' : null } |
  { 'instrumentation' : null };
export interface Equipment {
  'model' : string,
  'manufacturer' : string,
  'discipline' : EngineeringDiscipline,
  'purchaseDate' : Time,
  'additionalInformation' : string,
  'name' : string,
  'equipmentNumber' : bigint,
  'serialNumber' : string,
  'warrantyExpiry' : Time,
  'location' : string,
  'equipmentTagNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface MaintenanceRecord {
  'maintenanceStatus' : { 'scheduled' : null } |
    { 'completed' : null } |
    { 'overdue' : null },
  'additionalInformation' : string,
  'equipmentNumber' : bigint,
  'maintenanceType' : string,
  'maintenanceId' : bigint,
  'nextMaintenanceDate' : Time,
  'lastMaintenanceDate' : Time,
}
export interface SparePart {
  'manufacturer' : string,
  'partNumber' : bigint,
  'supplier' : string,
  'additionalInformation' : string,
  'name' : string,
  'description' : string,
  'modelSerial' : string,
  'quantity' : bigint,
  'attachment' : [] | [ExternalBlob],
  'manufacturerPartNo' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'department' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateSparePart' : ActorMethod<[SparePart, bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEquipment' : ActorMethod<[Equipment], boolean>,
  'createSparePart' : ActorMethod<[SparePart], boolean>,
  'deleteDocument' : ActorMethod<[bigint, bigint], boolean>,
  'deleteEquipment' : ActorMethod<[bigint], boolean>,
  'deleteSparePartByPartNumber' : ActorMethod<[bigint], boolean>,
  'findEquipmentByMatching' : ActorMethod<
    [string, boolean, boolean, boolean, boolean, boolean],
    Array<Equipment>
  >,
  'findSparePartByMatching' : ActorMethod<
    [string, boolean, boolean, boolean],
    Array<SparePart>
  >,
  'getAllCataloguingRecords' : ActorMethod<[bigint], Array<CataloguingRecord>>,
  'getAllDocuments' : ActorMethod<[bigint], Array<Document>>,
  'getAllEquipment' : ActorMethod<[], Array<Equipment>>,
  'getAllMaintenanceRecords' : ActorMethod<[bigint], Array<MaintenanceRecord>>,
  'getAllSpareParts' : ActorMethod<[], Array<SparePart>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEquipment' : ActorMethod<[bigint], [] | [Equipment]>,
  'getSparePartsForEquipment' : ActorMethod<[bigint], Array<SparePart>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlinkSparePartFromEquipment' : ActorMethod<[bigint, bigint], boolean>,
  'updateCataloguingRecord' : ActorMethod<[CataloguingRecord], boolean>,
  'updateEquipment' : ActorMethod<[Equipment], boolean>,
  'updateMaintenanceRecord' : ActorMethod<[MaintenanceRecord], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];