/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SparePart = IDL.Record({
  'manufacturer' : IDL.Text,
  'partNumber' : IDL.Nat,
  'supplier' : IDL.Text,
  'additionalInformation' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'modelSerial' : IDL.Text,
  'quantity' : IDL.Nat,
  'attachment' : IDL.Opt(ExternalBlob),
  'manufacturerPartNo' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EngineeringDiscipline = IDL.Variant({
  'mechanical' : IDL.Null,
  'piping' : IDL.Null,
  'electrical' : IDL.Null,
  'unknown' : IDL.Null,
  'instrumentation' : IDL.Null,
});
export const Time = IDL.Int;
export const Equipment = IDL.Record({
  'model' : IDL.Text,
  'manufacturer' : IDL.Text,
  'discipline' : EngineeringDiscipline,
  'purchaseDate' : Time,
  'additionalInformation' : IDL.Text,
  'name' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'serialNumber' : IDL.Text,
  'warrantyExpiry' : Time,
  'location' : IDL.Text,
  'equipmentTagNumber' : IDL.Text,
});
export const AdminRoleInfo = IDL.Record({
  'roleType' : IDL.Text,
  'adminPrincipal' : IDL.Principal,
  'isAdmin' : IDL.Bool,
});
export const CataloguingRecord = IDL.Record({
  'status' : IDL.Variant({ 'submitted' : IDL.Null, 'draft' : IDL.Null }),
  'additionalInformation' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'templateName' : IDL.Text,
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'materialDescription' : IDL.Text,
});
export const Document = IDL.Record({
  'documentType' : IDL.Text,
  'additionalInformation' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'filePath' : ExternalBlob,
  'docId' : IDL.Nat,
  'uploadDate' : Time,
});
export const MaintenanceRecord = IDL.Record({
  'maintenanceStatus' : IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
  }),
  'additionalInformation' : IDL.Text,
  'equipmentNumber' : IDL.Nat,
  'maintenanceType' : IDL.Text,
  'maintenanceId' : IDL.Nat,
  'nextMaintenanceDate' : Time,
  'lastMaintenanceDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateSparePart' : IDL.Func([SparePart, IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEquipment' : IDL.Func([Equipment], [IDL.Bool], []),
  'createSparePart' : IDL.Func([SparePart], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteEquipment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSparePartByPartNumber' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'findEquipmentByMatching' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Vec(Equipment)],
      ['query'],
    ),
  'findSparePartByMatching' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'getAdminRole' : IDL.Func([IDL.Principal], [AdminRoleInfo], ['query']),
  'getAllCataloguingRecords' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CataloguingRecord)],
      ['query'],
    ),
  'getAllDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
  'getAllMaintenanceRecords' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MaintenanceRecord)],
      ['query'],
    ),
  'getAllSpareParts' : IDL.Func([], [IDL.Vec(SparePart)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEquipment' : IDL.Func([IDL.Nat], [IDL.Opt(Equipment)], ['query']),
  'getSparePartsForEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SparePart)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importAttributeTemplateFromExcel' : IDL.Func(
      [ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlinkSparePartFromEquipment' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateCataloguingRecord' : IDL.Func([CataloguingRecord], [IDL.Bool], []),
  'updateEquipment' : IDL.Func([Equipment], [IDL.Bool], []),
  'updateMaintenanceRecord' : IDL.Func([MaintenanceRecord], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SparePart = IDL.Record({
    'manufacturer' : IDL.Text,
    'partNumber' : IDL.Nat,
    'supplier' : IDL.Text,
    'additionalInformation' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'modelSerial' : IDL.Text,
    'quantity' : IDL.Nat,
    'attachment' : IDL.Opt(ExternalBlob),
    'manufacturerPartNo' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EngineeringDiscipline = IDL.Variant({
    'mechanical' : IDL.Null,
    'piping' : IDL.Null,
    'electrical' : IDL.Null,
    'unknown' : IDL.Null,
    'instrumentation' : IDL.Null,
  });
  const Time = IDL.Int;
  const Equipment = IDL.Record({
    'model' : IDL.Text,
    'manufacturer' : IDL.Text,
    'discipline' : EngineeringDiscipline,
    'purchaseDate' : Time,
    'additionalInformation' : IDL.Text,
    'name' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'serialNumber' : IDL.Text,
    'warrantyExpiry' : Time,
    'location' : IDL.Text,
    'equipmentTagNumber' : IDL.Text,
  });
  const AdminRoleInfo = IDL.Record({
    'roleType' : IDL.Text,
    'adminPrincipal' : IDL.Principal,
    'isAdmin' : IDL.Bool,
  });
  const CataloguingRecord = IDL.Record({
    'status' : IDL.Variant({ 'submitted' : IDL.Null, 'draft' : IDL.Null }),
    'additionalInformation' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'templateName' : IDL.Text,
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'materialDescription' : IDL.Text,
  });
  const Document = IDL.Record({
    'documentType' : IDL.Text,
    'additionalInformation' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'filePath' : ExternalBlob,
    'docId' : IDL.Nat,
    'uploadDate' : Time,
  });
  const MaintenanceRecord = IDL.Record({
    'maintenanceStatus' : IDL.Variant({
      'scheduled' : IDL.Null,
      'completed' : IDL.Null,
      'overdue' : IDL.Null,
    }),
    'additionalInformation' : IDL.Text,
    'equipmentNumber' : IDL.Nat,
    'maintenanceType' : IDL.Text,
    'maintenanceId' : IDL.Nat,
    'nextMaintenanceDate' : Time,
    'lastMaintenanceDate' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateSparePart' : IDL.Func([SparePart, IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEquipment' : IDL.Func([Equipment], [IDL.Bool], []),
    'createSparePart' : IDL.Func([SparePart], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteEquipment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSparePartByPartNumber' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'findEquipmentByMatching' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Vec(Equipment)],
        ['query'],
      ),
    'findSparePartByMatching' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'getAdminRole' : IDL.Func([IDL.Principal], [AdminRoleInfo], ['query']),
    'getAllCataloguingRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CataloguingRecord)],
        ['query'],
      ),
    'getAllDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
    'getAllEquipment' : IDL.Func([], [IDL.Vec(Equipment)], ['query']),
    'getAllMaintenanceRecords' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MaintenanceRecord)],
        ['query'],
      ),
    'getAllSpareParts' : IDL.Func([], [IDL.Vec(SparePart)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEquipment' : IDL.Func([IDL.Nat], [IDL.Opt(Equipment)], ['query']),
    'getSparePartsForEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SparePart)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importAttributeTemplateFromExcel' : IDL.Func(
        [ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlinkSparePartFromEquipment' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateCataloguingRecord' : IDL.Func([CataloguingRecord], [IDL.Bool], []),
    'updateEquipment' : IDL.Func([Equipment], [IDL.Bool], []),
    'updateMaintenanceRecord' : IDL.Func([MaintenanceRecord], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };