/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Document {
    documentType: string;
    additionalInformation: string;
    equipmentNumber: bigint;
    filePath: ExternalBlob;
    docId: bigint;
    uploadDate: Time;
}
export interface CataloguingRecord {
    status: Variant_submitted_draft;
    additionalInformation: string;
    equipmentNumber: bigint;
    templateName: string;
    attributes: Array<[string, string]>;
    materialDescription: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MaintenanceRecord {
    maintenanceStatus: Variant_scheduled_completed_overdue;
    additionalInformation: string;
    equipmentNumber: bigint;
    maintenanceType: string;
    maintenanceId: bigint;
    nextMaintenanceDate: Time;
    lastMaintenanceDate: Time;
}
export interface Equipment {
    model: string;
    manufacturer: string;
    discipline: EngineeringDiscipline;
    purchaseDate: Time;
    additionalInformation: string;
    name: string;
    equipmentNumber: bigint;
    serialNumber: string;
    warrantyExpiry: Time;
    location: string;
    equipmentTagNumber: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SparePart {
    manufacturer: string;
    partNumber: bigint;
    supplier: string;
    additionalInformation: string;
    name: string;
    equipmentNumber: bigint;
    description: string;
    modelSerial: string;
    quantity: bigint;
    attachment?: ExternalBlob;
    partNo: string;
}
export interface UserProfile {
    name: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EngineeringDiscipline {
    mechanical = "mechanical",
    piping = "piping",
    electrical = "electrical",
    unknown_ = "unknown",
    instrumentation = "instrumentation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_scheduled_completed_overdue {
    scheduled = "scheduled",
    completed = "completed",
    overdue = "overdue"
}
export enum Variant_submitted_draft {
    submitted = "submitted",
    draft = "draft"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCataloguingRecord(equipmentNumber: bigint, materialDesc: string, templateName: string, attributes: Array<[string, string]>, isDraft: boolean, additionalInfo: string): Promise<bigint | null>;
    createEquipment(name: string, equipmentTagNumber: string, location: string, manufacturer: string, model: string, serial: string, purchase: Time, warranty: Time, additionalInfo: string, discipline: EngineeringDiscipline): Promise<bigint>;
    createMaintenanceRecord(equipmentNumber: bigint, maintType: string, status: Variant_scheduled_completed_overdue, lastDate: Time, nextDate: Time, additionalInfo: string): Promise<bigint | null>;
    createSparePart(equipmentNumber: bigint, name: string, description: string, quantity: bigint, supplier: string, manufacturer: string, partNo: string, modelSerial: string, attachment: ExternalBlob | null, additionalInfo: string): Promise<bigint | null>;
    deleteCataloguingRecord(equipmentNumber: bigint, recordIndex: bigint): Promise<boolean>;
    deleteDocument(equipmentNumber: bigint, docId: bigint): Promise<boolean>;
    deleteEquipment(equipmentNumber: bigint): Promise<boolean>;
    deleteMaintenanceRecord(equipmentNumber: bigint, maintenanceId: bigint): Promise<boolean>;
    deleteSparePart(equipmentNumber: bigint, partNumber: bigint): Promise<boolean>;
    findSparePartsByEquipmentTagNumber(_equipmentTagNumber: string): Promise<Array<SparePart>>;
    findSparePartsByManufacturer(manufacturer: string): Promise<Array<SparePart>>;
    findSparePartsByModelSerial(modelSerial: string): Promise<Array<SparePart>>;
    findSparePartsByPartNo(partNo: string): Promise<Array<SparePart>>;
    getAllEquipment(): Promise<Array<Equipment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCataloguingRecordsByEquipment(equipmentNumber: bigint): Promise<Array<CataloguingRecord>>;
    getDocumentsByEquipment(equipmentNumber: bigint): Promise<Array<Document>>;
    getEquipment(equipmentNumber: bigint): Promise<Equipment | null>;
    getEquipmentList(): Promise<Array<Equipment>>;
    getMaintenanceByEquipment(equipmentNumber: bigint): Promise<Array<MaintenanceRecord>>;
    getMaintenanceDueReport(): Promise<Array<MaintenanceRecord>>;
    getNextEquipmentNumber(): Promise<bigint>;
    getSparePartsByEquipment(equipmentNumber: bigint): Promise<Array<SparePart>>;
    getSparePartsReport(): Promise<Array<SparePart>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCataloguingRecord(equipmentNumber: bigint, recordIndex: bigint, materialDesc: string, templateName: string, attributes: Array<[string, string]>, isDraft: boolean, additionalInfo: string): Promise<boolean>;
    updateDocumentMetadata(equipmentNumber: bigint, docId: bigint, newDocType: string, additionalInfo: string): Promise<boolean>;
    updateEquipment(equipmentNumber: bigint, name: string, equipmentTagNumber: string, location: string, manufacturer: string, model: string, serial: string, purchase: Time, warranty: Time, additionalInfo: string, discipline: EngineeringDiscipline): Promise<boolean>;
    updateMaintenanceRecord(equipmentNumber: bigint, maintenanceId: bigint, maintType: string, status: Variant_scheduled_completed_overdue, lastDate: Time, nextDate: Time, additionalInfo: string): Promise<boolean>;
    updateSparePart(equipmentNumber: bigint, partNumber: bigint, name: string, description: string, quantity: bigint, supplier: string, manufacturer: string, partNo: string, modelSerial: string, attachment: ExternalBlob | null, additionalInfo: string): Promise<boolean>;
    uploadDocument(equipmentNumber: bigint, docType: string, file: ExternalBlob, additionalInfo: string): Promise<bigint | null>;
}
import type { CataloguingRecord as _CataloguingRecord, Document as _Document, EngineeringDiscipline as _EngineeringDiscipline, Equipment as _Equipment, ExternalBlob as _ExternalBlob, MaintenanceRecord as _MaintenanceRecord, SparePart as _SparePart, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCataloguingRecord(arg0: bigint, arg1: string, arg2: string, arg3: Array<[string, string]>, arg4: boolean, arg5: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createCataloguingRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCataloguingRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEquipment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Time, arg7: Time, arg8: string, arg9: EngineeringDiscipline): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEquipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_EngineeringDiscipline_n10(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEquipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_EngineeringDiscipline_n10(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async createMaintenanceRecord(arg0: bigint, arg1: string, arg2: Variant_scheduled_completed_overdue, arg3: Time, arg4: Time, arg5: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaintenanceRecord(arg0, arg1, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaintenanceRecord(arg0, arg1, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSparePart(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: ExternalBlob | null, arg9: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createSparePart(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg8), arg9);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSparePart(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg8), arg9);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCataloguingRecord(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCataloguingRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCataloguingRecord(arg0, arg1);
            return result;
        }
    }
    async deleteDocument(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0, arg1);
            return result;
        }
    }
    async deleteEquipment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEquipment(arg0);
            return result;
        }
    }
    async deleteMaintenanceRecord(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaintenanceRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaintenanceRecord(arg0, arg1);
            return result;
        }
    }
    async deleteSparePart(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSparePart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSparePart(arg0, arg1);
            return result;
        }
    }
    async findSparePartsByEquipmentTagNumber(arg0: string): Promise<Array<SparePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.findSparePartsByEquipmentTagNumber(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findSparePartsByEquipmentTagNumber(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async findSparePartsByManufacturer(arg0: string): Promise<Array<SparePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.findSparePartsByManufacturer(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findSparePartsByManufacturer(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async findSparePartsByModelSerial(arg0: string): Promise<Array<SparePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.findSparePartsByModelSerial(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findSparePartsByModelSerial(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async findSparePartsByPartNo(arg0: string): Promise<Array<SparePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.findSparePartsByPartNo(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findSparePartsByPartNo(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEquipment(): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEquipment();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEquipment();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCataloguingRecordsByEquipment(arg0: bigint): Promise<Array<CataloguingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCataloguingRecordsByEquipment(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCataloguingRecordsByEquipment(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsByEquipment(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByEquipment(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByEquipment(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquipment(arg0: bigint): Promise<Equipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipment(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipment(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquipmentList(): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentList();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentList();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceByEquipment(arg0: bigint): Promise<Array<MaintenanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceByEquipment(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceByEquipment(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceDueReport(): Promise<Array<MaintenanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceDueReport();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceDueReport();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextEquipmentNumber(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextEquipmentNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextEquipmentNumber();
            return result;
        }
    }
    async getSparePartsByEquipment(arg0: bigint): Promise<Array<SparePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSparePartsByEquipment(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSparePartsByEquipment(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSparePartsReport(): Promise<Array<SparePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSparePartsReport();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSparePartsReport();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCataloguingRecord(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: Array<[string, string]>, arg5: boolean, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCataloguingRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCataloguingRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateDocumentMetadata(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocumentMetadata(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocumentMetadata(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateEquipment(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Time, arg8: Time, arg9: string, arg10: EngineeringDiscipline): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEquipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_EngineeringDiscipline_n10(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEquipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_EngineeringDiscipline_n10(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async updateMaintenanceRecord(arg0: bigint, arg1: bigint, arg2: string, arg3: Variant_scheduled_completed_overdue, arg4: Time, arg5: Time, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenanceRecord(arg0, arg1, arg2, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenanceRecord(arg0, arg1, arg2, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updateSparePart(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string, arg9: ExternalBlob | null, arg10: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSparePart(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSparePart(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
    async uploadDocument(arg0: bigint, arg1: string, arg2: ExternalBlob, arg3: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CataloguingRecord_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CataloguingRecord): CataloguingRecord {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_EngineeringDiscipline_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EngineeringDiscipline): EngineeringDiscipline {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Equipment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Equipment): Equipment {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MaintenanceRecord_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceRecord): MaintenanceRecord {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_SparePart_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SparePart): Promise<SparePart> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Equipment]): Equipment | null {
    return value.length === 0 ? null : from_candid_Equipment_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manufacturer: string;
    partNumber: bigint;
    supplier: string;
    additionalInformation: string;
    name: string;
    equipmentNumber: bigint;
    description: string;
    modelSerial: string;
    quantity: bigint;
    attachment: [] | [_ExternalBlob];
    partNo: string;
}): Promise<{
    manufacturer: string;
    partNumber: bigint;
    supplier: string;
    additionalInformation: string;
    name: string;
    equipmentNumber: bigint;
    description: string;
    modelSerial: string;
    quantity: bigint;
    attachment?: ExternalBlob;
    partNo: string;
}> {
    return {
        manufacturer: value.manufacturer,
        partNumber: value.partNumber,
        supplier: value.supplier,
        additionalInformation: value.additionalInformation,
        name: value.name,
        equipmentNumber: value.equipmentNumber,
        description: value.description,
        modelSerial: value.modelSerial,
        quantity: value.quantity,
        attachment: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.attachment)),
        partNo: value.partNo
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    model: string;
    manufacturer: string;
    discipline: _EngineeringDiscipline;
    purchaseDate: _Time;
    additionalInformation: string;
    name: string;
    equipmentNumber: bigint;
    serialNumber: string;
    warrantyExpiry: _Time;
    location: string;
    equipmentTagNumber: string;
}): {
    model: string;
    manufacturer: string;
    discipline: EngineeringDiscipline;
    purchaseDate: Time;
    additionalInformation: string;
    name: string;
    equipmentNumber: bigint;
    serialNumber: string;
    warrantyExpiry: Time;
    location: string;
    equipmentTagNumber: string;
} {
    return {
        model: value.model,
        manufacturer: value.manufacturer,
        discipline: from_candid_EngineeringDiscipline_n23(_uploadFile, _downloadFile, value.discipline),
        purchaseDate: value.purchaseDate,
        additionalInformation: value.additionalInformation,
        name: value.name,
        equipmentNumber: value.equipmentNumber,
        serialNumber: value.serialNumber,
        warrantyExpiry: value.warrantyExpiry,
        location: value.location,
        equipmentTagNumber: value.equipmentTagNumber
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        submitted: null;
    } | {
        draft: null;
    };
    additionalInformation: string;
    equipmentNumber: bigint;
    templateName: string;
    attributes: Array<[string, string]>;
    materialDescription: string;
}): {
    status: Variant_submitted_draft;
    additionalInformation: string;
    equipmentNumber: bigint;
    templateName: string;
    attributes: Array<[string, string]>;
    materialDescription: string;
} {
    return {
        status: from_candid_variant_n31(_uploadFile, _downloadFile, value.status),
        additionalInformation: value.additionalInformation,
        equipmentNumber: value.equipmentNumber,
        templateName: value.templateName,
        attributes: value.attributes,
        materialDescription: value.materialDescription
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documentType: string;
    additionalInformation: string;
    equipmentNumber: bigint;
    filePath: _ExternalBlob;
    docId: bigint;
    uploadDate: _Time;
}): Promise<{
    documentType: string;
    additionalInformation: string;
    equipmentNumber: bigint;
    filePath: ExternalBlob;
    docId: bigint;
    uploadDate: Time;
}> {
    return {
        documentType: value.documentType,
        additionalInformation: value.additionalInformation,
        equipmentNumber: value.equipmentNumber,
        filePath: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.filePath),
        docId: value.docId,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maintenanceStatus: {
        scheduled: null;
    } | {
        completed: null;
    } | {
        overdue: null;
    };
    additionalInformation: string;
    equipmentNumber: bigint;
    maintenanceType: string;
    maintenanceId: bigint;
    nextMaintenanceDate: _Time;
    lastMaintenanceDate: _Time;
}): {
    maintenanceStatus: Variant_scheduled_completed_overdue;
    additionalInformation: string;
    equipmentNumber: bigint;
    maintenanceType: string;
    maintenanceId: bigint;
    nextMaintenanceDate: Time;
    lastMaintenanceDate: Time;
} {
    return {
        maintenanceStatus: from_candid_variant_n39(_uploadFile, _downloadFile, value.maintenanceStatus),
        additionalInformation: value.additionalInformation,
        equipmentNumber: value.equipmentNumber,
        maintenanceType: value.maintenanceType,
        maintenanceId: value.maintenanceId,
        nextMaintenanceDate: value.nextMaintenanceDate,
        lastMaintenanceDate: value.lastMaintenanceDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mechanical: null;
} | {
    piping: null;
} | {
    electrical: null;
} | {
    unknown: null;
} | {
    instrumentation: null;
}): EngineeringDiscipline {
    return "mechanical" in value ? EngineeringDiscipline.mechanical : "piping" in value ? EngineeringDiscipline.piping : "electrical" in value ? EngineeringDiscipline.electrical : "unknown" in value ? EngineeringDiscipline.unknown : "instrumentation" in value ? EngineeringDiscipline.instrumentation : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    draft: null;
}): Variant_submitted_draft {
    return "submitted" in value ? Variant_submitted_draft.submitted : "draft" in value ? Variant_submitted_draft.draft : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    completed: null;
} | {
    overdue: null;
}): Variant_scheduled_completed_overdue {
    return "scheduled" in value ? Variant_scheduled_completed_overdue.scheduled : "completed" in value ? Variant_scheduled_completed_overdue.completed : "overdue" in value ? Variant_scheduled_completed_overdue.overdue : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SparePart>): Promise<Array<SparePart>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SparePart_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Equipment>): Array<Equipment> {
    return value.map((x)=>from_candid_Equipment_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CataloguingRecord>): Array<CataloguingRecord> {
    return value.map((x)=>from_candid_CataloguingRecord_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n33(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaintenanceRecord>): Array<MaintenanceRecord> {
    return value.map((x)=>from_candid_MaintenanceRecord_n37(_uploadFile, _downloadFile, x));
}
function to_candid_EngineeringDiscipline_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngineeringDiscipline): _EngineeringDiscipline {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngineeringDiscipline): {
    mechanical: null;
} | {
    piping: null;
} | {
    electrical: null;
} | {
    unknown: null;
} | {
    instrumentation: null;
} {
    return value == EngineeringDiscipline.mechanical ? {
        mechanical: null
    } : value == EngineeringDiscipline.piping ? {
        piping: null
    } : value == EngineeringDiscipline.electrical ? {
        electrical: null
    } : value == EngineeringDiscipline.unknown ? {
        unknown_: null
    } : value == EngineeringDiscipline.instrumentation ? {
        instrumentation: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_scheduled_completed_overdue): {
    scheduled: null;
} | {
    completed: null;
} | {
    overdue: null;
} {
    return value == Variant_scheduled_completed_overdue.scheduled ? {
        scheduled: null
    } : value == Variant_scheduled_completed_overdue.completed ? {
        completed: null
    } : value == Variant_scheduled_completed_overdue.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
